version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/build
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          DOCKER_IMAGE="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
          DOCKER_TAG="$CIRCLE_SHA1"
          NODE_VERSION="10.15.3"
          docker info
          docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
          if [ "$CIRCLE_BRANCH" = "master" ]; then
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
            docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:$NODE_VERSION
            docker push $DOCKER_IMAGE:$DOCKER_TAG
            docker push $DOCKER_IMAGE:$NODE_VERSION
            docker push $DOCKER_IMAGE:latest
          fi

workflows:
  version: 2
  primary:
    jobs:
      - build
